### ISSUE TITLE
cococ2d-x integration for heyzap

### ISSUE THREAD

**Issue by sidshekar** [Heyzap/ios-example-app#1]
Hi are you guys making a cocos2d-x version with android and ios? I mean since you already have for iOS and android you just would have to make common c++ class which talks to both obj-c and java???

I could but by java is a bit weak... could do for ios tho.... :)

**Comment by immad** [comment]
We don't currently have a cocos2d-x implementation. It is something we are considering and have some of the basics for. 

If we put up something not fully tested up on a Github repo can you help us get it fully working?

**Comment by sidshekar** [comment]
Ya sure. I am currently making a multiplatform game for iOS android and
windows mobile using cocos2d-x I will integrate it in it.

**Comment by immad** [comment]
Great. Will let you know when we have something

**Comment by sidshekar** [comment]
Sure. K. Thanks.

**Comment by sidshekar** [comment]
Hi!! did you guys make any progress in making it for cocos2d-x??!??!

**Comment by sidshekar** [comment]
Siddharth Shekar sent you an invitation
Twitter helps you stay connected with what's happening right now and with the people and organizations you care about.

  Accept invitation

https://twitter.com/i/00547de0-13b3-4df2-b971-11ae779ff424

## 

You can unsubscribe from receiving email notifications from Twitter at anytime. For general inquiries, please visit us at Twitter Support.
Unsubscribe: https://twitter.com/i/o?t=1&iid=8ad5ef02df83470fa28287890ece855e&uid=0&c=IuVwbCB3dgGkLVmJmZJKLzpc5vgKnv2i1PO%2BXt2Xud2yUVXMDIrJiGqfLw3ePvVuNMWDFPBT%2BIT0%2BU%2Bg431QyL%2BYbVb4HHVwj6qSzubtoDWdTjSYFb27Lg%3D%3D&nid=244+26

Need help?
https://support.twitter.com
