### ISSUE TITLE
Heyzap ios Native ads tap issue

### ISSUE THREAD

**Issue by amacymind** [Heyzap/ios-example-app#12]
Hello,
I try to implement Heyzap native ads in my app. Here's you guide for that, https://developers.heyzap.com/docs/ios_sdk_native_mediation
I receive ads successfully but tap on that not working. Means if i tap on titlelabel,body,icon,etc then nothing happen.
Please check it & let me know anything missing.
If any example for that then provide me.

**Comment by itaysagivfyber** [comment]
Dear @amacymind 
I am sorry to hear you faced some issues with our native ads.
Please note that we are stopping the support for this ad type in our system.
Public communication and documentation updates are in progress.
We would be happy to support you with any other query you have.

Have a wonderful day,
Itay, Director of Product Management, Head of Mobile Products
