### ISSUE TITLE
Vungle + adcolony error

### ISSUE THREAD

**Issue by purepure** [Heyzap/ios-example-app#3]
I try to use vungle and adcolony but whenever I add them into project I get error
ndefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_WKWebView", referenced from:
      l_OBJC_$_CATEGORY_WKWebView_$_VungleWKWebView in VungleSDK(WKWebView+VungleWKWebView.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

The other lib is ok

Please take a look and help to point out direction

Thank

**Comment by purepure** [comment]
hey guy! any update on this ?

**Comment by MaxGabriel** [comment]
It sounds like WebKit.framework needs to be added. Can you try doing that? I've had issues doing `@import WebKit;`—you may need to manually add WebKit from the Xcode project UI.

**Comment by purepure** [comment]
@MaxGabriel : thank you guy. It works!

P/s: I think so many user will get this issue until heyzap fix its, so I leave this here without closing it. When heyzap team provide fix, they will close this one

BR
